# Generated by Django 4.0.4 on 2023-01-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='phone',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
