# Generated by Django 4.0.4 on 2023-01-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='number',
            field=models.IntegerField(),
        ),
    ]
