# Generated by Django 4.0.4 on 2023-01-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_blog_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
