# Generated by Django 4.0.4 on 2023-01-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_blog_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.TextField(default='제목', max_length=80),
        ),
        migrations.AlterField(
            model_name='blog',
            name='writer',
            field=models.CharField(max_length=20),
        ),
    ]
