# Generated by Django 4.0.4 on 2023-01-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_blog_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.TextField(max_length=15),
        ),
    ]
